apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: supinfo4kube/queue:1.0.1
          ports:
            - containerPort: 8161
            - containerPort: 61616
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice"
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
    - name: port-8161  # Nom donné au port
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: port-61616  # Nom donné au port
      protocol: TCP
      port: 61616
      targetPort: 61616
  type: ClusterIP
