apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-mongo
  labels:
    app: fleetman-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongo
  template:
    metadata:
      labels:
        app: fleetman-mongo
    spec:
      containers:
        - name: fleetman-mongo
          image: mongo:3.6.23
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: fleetman-mongo
