apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
  labels:
    app: fleetman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: supinfo4kube/queue:1.0.1
          ports:
            - containerPort: 8161
            - containerPort: 61616
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice"
          volumeMounts:
            - name: queue-data
              mountPath: /data  # Chemin dans le conteneur où le volume sera monté
      volumes:
        - name: queue-data
          persistentVolumeClaim:
            claimName: queue-data-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: queue-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/queue  # Chemin sur le nœud Kubernetes pour stocker les données
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
    - name: port-8161  # Nom donné au port
      protocol: TCP
      port: 8161
      targetPort: 8161
    - name: port-61616  # Nom donné au port
      protocol: TCP
      port: 61616
      targetPort: 61616
  type: ClusterIP
