apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
  labels:
    app: fleetman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
        - name: position-simulator
          image: supinfo4kube/position-simulator:1.0.1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production-microservice" # Change for Kubernetes
          ports:
            - containerPort: 8080 # Replace with the actual port if required
          volumeMounts:
            - name: db-data
              mountPath: /data/db # Mount point inside the container
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db # Path on the host machine for local storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
